apiVersion: batch/v1
kind: Job
metadata:
  name: invoiceflow-prisma-db-push
  namespace: invoiceflow
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: prisma
          image: YOUR_DOCKERHUB_USERNAME/invoicebackend:latest
          command: ["npx", "prisma", "db", "push"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DATABASE_URL
  backoffLimit: 3