namespace: invoiceflow

backend:
  image:
    repository: xpocky/invoicebackend
    tag: v2
    pullPolicy: Always
  port: 5000

frontend:
  image:
    repository: xpocky/invoicefrontend
    tag: v2
    pullPolicy: Always
  port: 80

ingress:
  enabled: true
  className: traefik

secrets:
  existingSecret: invoiceflow-secrets