apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: invoiceflow
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/PrabalPiya/invoiceflow-devops-infrastructure.git
    targetRevision: main
    path: helm/invoiceflow

  destination:
    server: https://kubernetes.default.svc
    namespace: invoiceflow

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true