apiVersion: v1
kind: Service
metadata:
  name: invoicefrontend
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: invoicefrontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}