{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: invoiceflow-ingress
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: invoicebackend
                port:
                  number: {{ .Values.backend.port }}

          - path: /
            pathType: Prefix
            backend:
              service:
                name: invoicefrontend
                port:
                  number: {{ .Values.frontend.port }}
{{- end }}