apiVersion: v1
kind: Secret
metadata:
  name: invoiceflow-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.postgresUser }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword }}
  POSTGRES_DB: {{ .Values.secrets.postgresDb | quote }}
  DATABASE_URL: "postgresql://{{ .Values.secrets.postgresUser }}:{{ .Values.secrets.postgresPassword }}@invoicepostgres:5432/{{ .Values.secrets.postgresDb }}"
  JWT_SECRET: {{ .Values.secrets.jwtSecret }}
  JWT_EXPIRES_IN: {{ .Values.secrets.jwtExpiresIn }}
  